[tool.poetry]
name = "pynetdicom-prac"
version = "0.1.0"
description = ""
authors = ["SALEH846 <ranaasaleh846@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pynetdicom = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
